### PR TITLE
Enable auto-styling

### PR DESCRIPTION
**Pull request by krlmlr**
.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Hi @krlmlr, I see the autostyle action now in a few repos. Did you build it? Did you consider using [{precommit}](https://lorenzwalthert.github.io/precommit/dev/) instead? Patrick has introduced it in mlr repos now and we are gradually adding pre-commit.ci to those. Pre-commit can be ran locally, as CI service pre-commit.ci or via GitHub Actions.

* ran locally before on CI (i.e. on git commit).
* autofixes problems like styling.
* not just styling, any hook can be easily implemented.
* hooks from {precommit} are documented and extensively tested.
* building on the shoulders of giants (pre-commit.com) and abstract away a lot of logic not specific to R hooks.

But of course it's not as flexible as Building your own GitHub actions from scratch, eg when it comes to controlling the environment, system libraries etc.

**Comment by lorenzwalthert** [comment]
Also, I like the idea of specifying style in a config file. I worked on a generic approach for value resolution of local configs, env variables and R options in https://github.com/lorenzwalthert/fallback. Feel free to pick that up if you want, I don't have time to work on it anymore. There is also the idea of styler picking up values from a config file in https://github.com/r-lib/styler/issues/319, which also was not implemented due to the high effort and API changes.

**Comment by krlmlr** [comment]
Thanks, I did consider precommit. I like the way how styling via GitHub Actions doesn't impose any installation effort on the contributor.

I'm fine with config values stored in `DESCRIPTION` for now.

**Comment by lorenzwalthert** [comment]
Thanks for the quick answer.

>  I like the way how styling via GitHub Actions doesn't impose any installation effort on the contributor. 

That's a fair point and probably the main adaption obstacle for {precommit}. Note that a local user does not have to have any software related to pre-commit installed, the hooks can be enforced via pre-commit.ci or a respective GitHub Action.

**Comment by krlmlr** [comment]
Thanks for the hint. I'll check it out.

**Comment by lorenzwalthert** [comment]
If you have questions, you can message me anytime or open issues.

**Comment by krlmlr** [comment]
I decided to avoid precommit for now. I don't see myself using it locally, and I'd like to avoid depending on a third-party service for this functionality.

**Pull request merged**
